### ISSUE TITLE
Merge OS X and official version

### ISSUE THREAD

**Issue by filipre** [MumflrFumperdink/olcPGEMac#10]
Hi, 

given that the olcPixelEngine is still being developed, I wonder if there is a better way than maintaining *two* separate *complete* libraries which may diverge more and more. For example, one-lone-coder made several changes which are not in this version yet

```
2.01: Made renderer and platform static for multifile projects
2.02: Added Decal destructor, optimised Pixel constructor
2.03: Added FreeBSD flags, Added DrawStringDecal()
2.04: Windows Full-Screen bug fixed
2.05: Added DrawPartialWarpedDecal(), Added DrawPartialRotatedDecal()
```

Over time, it could become more and more difficult to merge these two versions. Especially, when one-lone-coder makes changes that are not well documented by him. Is there a current plan to tackle this problem? Or can you ellaborate where OS X specific code starts/finishes and where things just have been copied?

Best
René

**Comment by MumflrFumperdink** [comment]
Hi!

I have neglected to merge with the main engine because I have been hammering out some bugs with this version, although I am close to finishing. I have been told that this version might be merged in the future with the main version, so that might solve the problem. In the meantime, I should probably bring in those new commits (thanks for telling me).

I am hoping this should not take long because one big feature introduced in olcPixelEngine 2.0 was the platform class. Basically, this class (plus a little bit of code in the renderer class) handles all of the platform-specific functions for the PGE. This was done in order for the main PGE class to be platform-independent. So, any PGE functions should (hopefully) be easily transferrable, and I imagine most of the relevant updates to a Mac user would be in there.

P.S. the way I separate the code is with the __APPLE__ macro if you want to see where that is

**Comment by MumflrFumperdink** [comment]
I just made a commit that includes all the newest versions.

**Comment by filipre** [comment]
Wow! Thanks again for these features. Now the "dungeon warping" tutorial works without any additional modifications. 

Using that platform class in the future sounds good to me.

<img width="883" alt="Screenshot 2020-05-28 at 21 12 36" src="https://user-images.githubusercontent.com/8502198/83183369-f9810480-a127-11ea-9de9-c6ec87007a11.png">
