### ISSUE TITLE
Issue compiling for the OSx

### ISSUE THREAD

**Issue by bhupen** [MumflrFumperdink/olcPGEMac#7]
Tried compiling in Xcode and encountering and error 

"'experimental/filesystem' file not found" 

Could you suggest a solution?

**Comment by MumflrFumperdink** [comment]
What version of Xcode do you have? It could be that you need you upgrade to Xcode 11.

**Comment by sararyCow** [comment]
I'm facing the same problem. I have Xcode 11.3.1, can't upload to 11.4.1 because it only works in Catalina (and I don't want to upload to because of 32 bit apps).

<img width="642" alt="Captura de pantalla 2020-04-20 a las 13 42 10" src="https://user-images.githubusercontent.com/7062168/79748743-33cbda80-830e-11ea-92bd-c4a08b25c21b.png">

**Comment by MumflrFumperdink** [comment]
I am unsure of what the problem is but let's test some things. Can you type in both:
`ls /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1`
and 
`ls /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/experimental`
and tell me if you see "filesystem" in either?

**Comment by sararyCow** [comment]
Indeed I have `filesystem` in both:

<img width="570" alt="Captura de pantalla 2020-04-20 a las 22 06 44" src="https://user-images.githubusercontent.com/7062168/79794936-6ea43180-8353-11ea-8671-c63f9679ce08.png">

<img width="570" alt="Captura de pantalla 2020-04-20 a las 22 07 09" src="https://user-images.githubusercontent.com/7062168/79794944-7368e580-8353-11ea-9e16-fe9c0d76fba9.png">

I'm using macOS 14.14.6, maybe the problem is related to the need for the latest version of the operating system?

**Comment by MumflrFumperdink** [comment]
Well, you already have the headers so it should not be an os problem. Can you go into your project settings (blue icon at the top of files on the left with the name of your project) -> Build Settings and search for "C++ Language Dialect" and "C++ Standard Library"?

**Comment by sararyCow** [comment]
This is what I get:

<img width="633" alt="Captura de pantalla 2020-04-21 a las 21 36 59" src="https://user-images.githubusercontent.com/7062168/79906595-619d4600-8418-11ea-81e7-a238d65c96b2.png">

Complete sentence for C++ Standart Library is "libc++ (LLVM C++ Standart Library with C++11 support)"

I tried with GNU++17 and C++17 for Language Dialect and got the same result.

I was asking for OS compatibility because I wasn't using Xcode for building the project but just the Makefile provided, getting the "'experimental/filesystem' file not found". When I try to build it with Xcode this is what I get:

<img width="317" alt="Captura de pantalla 2020-04-20 a las 22 16 09" src="https://user-images.githubusercontent.com/7062168/79907329-b68d8c00-8419-11ea-9a69-acff52b09fe5.png">

**Comment by MumflrFumperdink** [comment]
Then it might actually be the OS version that is the problem. I think I will add that to the readme for others.
